[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
iswap = "9Hy6ivQ1LU4ZvAXKLUZZvCKDPCQfdKYHhjzMre9AnD2r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
api = "yarn run ts-node app/index.ts"
