[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
solana-client = "2.3.3"
solana-program = "2.3.0"
solana-sdk = "2.3.1"
spl-associated-token-account = "7.0.0"
spl-token = "8.0.0"
